
(function(){var t=document.querySelector('.menu-toggle'),n=document.querySelector('.navlinks');if(t&&n)t.onclick=function(){n.classList.toggle('open')}})();
function fmtDate(s){return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(s+'T12:00:00'));}
function esc(s){return String(s||'').replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]});}
function published(items){return items.filter(function(x){return x.status==='veroeffentlicht'}).sort(function(a,b){return b.datum.localeCompare(a.datum)});}
function renderArchive(type){var all=published(window.IDK_CONTENT[type]||[]),search=document.getElementById('search'),year=document.getElementById('year'),cat=document.getElementById('category'),root=document.getElementById('archive'),empty=document.getElementById('empty');
 [...new Set(all.map(x=>x.datum.slice(0,4)))].forEach(y=>year.insertAdjacentHTML('beforeend','<option>'+y+'</option>')); [...new Set(all.map(x=>x.kategorie))].sort().forEach(c=>cat.insertAdjacentHTML('beforeend','<option>'+esc(c)+'</option>'));
 function draw(){var q=search.value.toLowerCase(),ys=year.value,cs=cat.value,items=all.filter(x=>(ys==='all'||x.datum.startsWith(ys))&&(cs==='all'||x.kategorie===cs)&&(!q||(x.titel+' '+x.teaser+' '+x.kategorie).toLowerCase().includes(q)));var groups={};items.forEach(x=>(groups[x.datum.slice(0,4)]||(groups[x.datum.slice(0,4)]=[])).push(x));root.innerHTML='';Object.keys(groups).sort().reverse().forEach(y=>{var cards=groups[y].map(x=>card(x,type)).join('');root.insertAdjacentHTML('beforeend','<h2 class="archive-title">'+y+'</h2><div class="grid">'+cards+'</div>')});empty.style.display=items.length?'none':'block';}
 search.oninput=draw;year.onchange=draw;cat.onchange=draw;draw();}
function card(x,type){var url=(type==='gedanken'?'gedanke.html':'news-detail.html')+'?id='+encodeURIComponent(x.id);return '<article class="card"><a class="card-image" href="'+url+'"><img src="'+esc(x.bild)+'" alt="'+esc(x.bildAlt)+'" loading="lazy"></a><div class="card-body"><div class="meta"><span>'+fmtDate(x.datum)+'</span><span class="tag">'+esc(x.kategorie)+'</span></div><h2><a href="'+url+'">'+esc(x.titel)+'</a></h2><p>'+esc(x.teaser)+'</p><a class="more" href="'+url+'">Weiterlesen →</a></div></article>';}
function renderDetail(type){var id=new URLSearchParams(location.search).get('id'),x=published(window.IDK_CONTENT[type]||[]).find(a=>a.id===id),root=document.getElementById('detail');if(!x){root.innerHTML='<section class="article-head"><div class="container-narrow"><h1>Eintrag nicht gefunden.</h1><a class="back" href="'+(type==='gedanken'?'gedanken.html':'news.html')+'">← Zur Übersicht</a></div></section>';return;}document.title=x.titel+' | Ihsan David Khalil';var paras=(x.text||[]).map(p=>'<p>'+esc(p)+'</p>').join('');root.innerHTML='<article><header class="article-head"><div class="container-narrow"><span class="eyebrow">'+esc(x.kategorie)+'</span><div class="article-meta">'+fmtDate(x.datum)+' · '+esc(x.lesedauer||'')+'</div><h1>'+esc(x.titel)+'</h1></div></header><figure class="hero-image"><img src="'+esc(x.bild)+'" alt="'+esc(x.bildAlt)+'"></figure><div class="container-narrow"><blockquote class="article-quote">'+esc(x.zitat||'')+'</blockquote><div class="article-body">'+paras+'</div>'+(x.frage?'<div class="closing-question">'+esc(x.frage)+'</div>':'')+'<a class="back" href="'+(type==='gedanken'?'gedanken.html':'news.html')+'">← Zur Übersicht</a></div></article>';}
