
let data=JSON.parse(JSON.stringify(window.IDK_CONTENT)),current=null;const $=id=>document.getElementById(id);function slug(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function list(){let box=$('entries');box.innerHTML='';['gedanken','news'].forEach(type=>{let h=document.createElement('strong');h.textContent=type==='gedanken'?'Gedanken':'News';box.appendChild(h);data[type].forEach((x,i)=>{let b=document.createElement('button');b.type='button';b.textContent=(x.status==='entwurf'?'○ ':'● ')+x.titel;b.onclick=()=>load(type,i);box.appendChild(b)})})}
function blank(type){current={type,index:-1};$('form').reset();$('type').value=type;$('datum').value=new Date().toISOString().slice(0,10);$('status').value='entwurf';$('lesedauer').value=type==='news'?'2 Min.':'5 Min.'}
function load(type,index){current={type,index};let x=data[type][index];['id','status','datum','kategorie','titel','teaser','bild','bildAlt','lesedauer','zitat','frage'].forEach(k=>$(k).value=x[k]||'');$('type').value=type;$('text').value=(x.text||[]).join('\n\n')}
$('newThought').onclick=()=>blank('gedanken');$('newNews').onclick=()=>blank('news');$('titel').onblur=()=>{if(!$('id').value)$('id').value=slug($('titel').value)};
$('form').onsubmit=e=>{e.preventDefault();let type=$('type').value||'gedanken',x={};['id','status','datum','kategorie','titel','teaser','bild','bildAlt','lesedauer','zitat','frage'].forEach(k=>x[k]=$(k).value.trim());x.text=$('text').value.split(/\n\s*\n/).map(s=>s.trim()).filter(Boolean);if(current&&current.index>=0)data[type][current.index]=x;else{data[type].push(x);current={type,index:data[type].length-1}}list();alert('Gespeichert. Jetzt content.js herunterladen.')};
$('delete').onclick=()=>{if(!current||current.index<0)return;if(confirm('Eintrag wirklich löschen?')){data[current.type].splice(current.index,1);current=null;blank('gedanken');list()}};
$('download').onclick=()=>{let txt='window.IDK_CONTENT = '+JSON.stringify(data,null,2)+';\n',blob=new Blob([txt],{type:'text/javascript'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='content.js';a.click();URL.revokeObjectURL(a.href)};list();blank('gedanken');
